# Generated by Django 5.2.7 on 2025-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_rollno', models.IntegerField(default=0)),
                ('s_course', models.CharField(max_length=200)),
            ],
        ),
    ]
