# Generated by Django 5.2.5 on 2025-10-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_category', models.CharField(max_length=100)),
                ('p_name', models.CharField(max_length=100)),
                ('p_desc', models.CharField(max_length=100)),
                ('p_price', models.CharField(max_length=100)),
            ],
        ),
    ]
